### ISSUE TITLE
4.3.1 not exporting

### ISSUE THREAD

**Issue by valleyarchitect** [BIM-Tools/SketchUp-IFC-Manager#43]
Hi I just installed the 4.3.1 via .rbz and when testing an export, this is what I got in the RubyConsole:

"Error: #<NoMethodError: undefined method `representation=' for #<BimTools::IFC2X3::IfcPreDefinedPointMarkerSymbol:0x000002cc9f0a1158>>
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/ObjectCreator.rb:343:in `create_geometry'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/ObjectCreator.rb:125:in `create_ifc_entity'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/ObjectCreator.rb:71:in `initialize'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IfcModel.rb:229:in `new'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IfcModel.rb:229:in `create_ifc_objects'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/bt_ifcmanager/lib/lib_ifc/IfcModel.rb:133:in `initialize'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/bt_ifcmanager/export.rb:60:in `new'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/bt_ifcmanager/export.rb:60:in `export'
C:/Users/VIVARCHI/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/bt_ifcmanager/loader.rb:127:in `block in <module:IfcManager>'
c:/users/vivarchi/appdata/roaming/sketchup/sketchup 2022/sketchup/plugins/!!fredo6_lordofthetoolbars/controller_lordofthetoolbars.rbe:133:in `block in new'"

Not sure what's going on here :(

**Comment by janbrouwer** [comment]
I will add a catch for that, there is no support for the entity IfcPreDefinedPointMarkerSymbol, or send to be on your model somewhere.

https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/TC1/HTML/ifcpresentationdimensioningresource/lexical/ifcpredefinedpointmarkersymbol.htm

**Comment by valleyarchitect** [comment]
Hi, here is the test model I use...
[$-vivarchi-vierge-2022.zip](https://github.com/BIM-Tools/SketchUp-IFC-Manager/files/10043084/-vivarchi-vierge-2022.zip)

**Comment by valleyarchitect** [comment]
and here is the .ifc that I wasable to export using v3.5.0
[$-vivarchi-vierge350-2022.zip](https://github.com/BIM-Tools/SketchUp-IFC-Manager/files/10043099/-vivarchi-vierge350-2022.zip)

**Comment by janbrouwer** [comment]
Thanks, that confirms my suspicion.
I will fix it so it will not crash on it anymore.
IfcPreDefinedPointMarkerSymbol is a very obscure IFC type **without geometry** that's even removed in IFC4.
What 3.5.0 did was make an empty IfcPreDefinedPointMarkerSymbol, take out the geometry and make an IfcBuildingElementProxy from the geometry.
I advise to just use the IFC entity IfcBuildingElementProxy for the "$-repère-Origine" origin object.

**Comment by valleyarchitect** [comment]
Hi Jan, thanks for that feedback !  Do the folks at Trimble realise that you have single-handedly saved their Sketchup from BIM oblivion ?  Without you plugin we could not pretend to keep up, we'd be obliged to go learn Rev(olt)it ! or some other big and expensive stuff.  I mean the possibility of creating and importing correctly structured ifc files is the ABC... Anyway, many thanks and keep up the good work !

**Comment by valleyarchitect** [comment]
Just one slight niggle... I just checked, and whilst I can now export without the crash, the layers still do no transfer into the exported ifc despite the option being ticked in the preferences... what am I doing wrong ?
[$-vivarchi-vierge-2022-ifcM431.zip](https://github.com/BIM-Tools/SketchUp-IFC-Manager/files/10046891/-vivarchi-vierge-2022-ifcM431.zip)

**Comment by janbrouwer** [comment]
Thanks for the compliment!
I do see layers in your IFC file, can you show me what you expect to see?
<img width="1512" alt="Screenshot" src="https://user-images.githubusercontent.com/4561580/202851911-ae836099-9c8d-44c2-b231-b2c37a82a922.png">

**Comment by valleyarchitect** [comment]
Well, not in the ifc from 4.3.1
Here are the two ifc files, one from 350 & the other from 431 plus screenshots from eveBIM
[Documents.zip](https://github.com/BIM-Tools/SketchUp-IFC-Manager/files/10047052/Documents.zip)

**Comment by valleyarchitect** [comment]
Maybe it's an import problem with eveBIM ? But that would be odd as eveBIM interprets the 350 file correctly.
I'll download some other viewer software and have a look...

**Comment by janbrouwer** [comment]
I found it. In recent versions I attach the layer to the mapped shaperepresentation instead of the direct shaperepresentation, it seems that eveBIM doesn't recognize that. It might be better to revert that change, I will look into that.

**Comment by valleyarchitect** [comment]
Great, thanks.
I just tested in BimVision: it shows the layers, however in the 431 version it incorrectly identifies attributions (i tried rendering the wall layer invisible, and only the upper storey wall disappeared despite both walls being on the same layer...
However, it woks fine in the 350 version so I guess your mapping change does seem to make a difference !
![$-vivarchivierge-431-screenshot-inBimVision](https://user-images.githubusercontent.com/70261186/202855413-deebb444-c294-4495-9ff6-22e03c50b9c3.jpg)
![$-vivarchivierge-350-screenshot-inBimVision](https://user-images.githubusercontent.com/70261186/202855416-8fb5b783-35ed-4010-b8c4-a5c765ef920f.jpg)

**Comment by valleyarchitect** [comment]
...does the 431 version export "ifc.zones" ? it didn't seem to, but again, this might be an eveBIM issue.

**Comment by janbrouwer** [comment]
I just tested  zones by creating a couple of spaces and nesting those within a zone component and it showed up, even in the eveBIM version I just downloaded.

**Comment by valleyarchitect** [comment]
oh, right, great news, although one nice thing about eveBIM is that you can create zoning strategies even on ifc files without them from SU. Well, as soon as a 4.3.x version remaps the layers, I'll give it a go :)
Thanks for all your hard work, and have a good weekend, best regards, PT

**Comment by valleyarchitect** [comment]
Jan,  bad news I'm afraid... v4.3.3 was working fine til I updated to the latest SU2023 patch from 15th of March... 

& now I get messed-up ifc files.  I checked there was no other plugin messing things up by disactivating all but IFC Manager... no improvement, & I went back to version 3.4.7 of IFC Manager & the export was perfect...
I'd love to send you the test files, but they're too big for here, so I could send them via GrosFichiers or something if you send me an email address..

Best regards,
PT
